version: '3.7'

services:
    costdb:
        image: postgres:latest
        environment:
            POSTGRES_USER: sampleuser
            POSTGRES_PASSWORD: samplepassword
            POSTGRES_DB: costdb
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data: